jobs:
  inlcude:
    - stage: test
      name: python tests
      language: python
      python:
        - "2.7"
        - "3.6"
      install:
        - pip install tox-travis
        - pip install coveralls
      after_success:
        coveralls
      script: 
        - tox
    - stage: test
      name: "js tests"
      language: node_js
      node_js:
        - '10.15.2'
      cache:
        npm: true
      install:
        - npm install
      script:
        - npm test