version: 2

jobs:
  build-py:
    docker:
      - image: cimg/python:3.9.2
    working_directory: ~/py
    steps:
      - checkout
      - run: cat requirements/*.txt > all.txt
      - run: cat all.txt
      - restore_cache:
          keys:
            - py-dependencies-{{ checksum "all.txt" }}
      - run: pip install tox
      - run: tox
      - save_cache:
          paths:
            - ".tox"
            - ".eggs"
          key: py-dependencies-{{ checksum "all.txt" }}
  build-js:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/js
    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: js-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: npm test
workflows:
  version: 2
  test:
    jobs:
      - build-py
      - build-js
